---
all:
  hosts:
    el-instance:
      ansible_host: 51.250.12.156
    k-instance:
      ansible_host: 51.250.3.76
    app-instance:
      ansible_host: 51.250.9.0
  vars:
    ansible_connection: ssh
    ansible_user: at6man
elasticsearch:
  hosts:
    el-instance:
kibana:
  hosts:
    k-instance:
app:
  hosts:
    app-instance: