---
  - src: git@github.com:netology-code/mnt-homeworks-ansible.git
    scm: git
    version: "2.0.0"
    name: elastic 
  - src: git@github.com:at6man/kibana-role.git
    scm: git
    version: "1.0.2"
    name: kibana-role 
  - src: git@github.com:at6man/filebeat-role.git
    scm: git
    version: "1.0.1"
    name: filebeat-role 