---
- name: Install Elasticsearch
  hosts: elasticsearch
  roles:
    - elastic
      
- name: Install Kibana
  hosts: kibana
  roles:
    - kibana-role
      
- name: Install filebeat
  hosts: app
  roles:
    - filebeat-role
